theres is a ball
ddddddddddd
eeeemmmmmmmmmmmmmmmmmmmmmmmmm
wwwwwww
jjjjjjjjjjjmmmmmmmmmmmmmmmmjjmmmmmmmmmmmmmmmmmmmmmm
dmmmmmmmmmmmmmmmmmmmmmmm
ddkkkkk
jjjjjjjjjjjjjjjj,mmmmmmmmmmmmmmmjj
dhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
dsssss
d
d
