theres is a ball
ddddddddddd
eeeemmmmmmmmmmmmmmmmmmmmmmmmm
wwwwwww
jjjjjjjjjjjmmmmmmmmmmmmmmmmjjmmmmmmmmmmmmmmmmmmmmmm
dmmmmmmmmmmmmmmmmmmmmmmm
ddkkkkk
jjjjjjjjjjjjjjjj,mmmmmmmmmmmmmmmjj
d
dsssss
d
d
